Tirelires/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tirelires.DataAcess;

namespace Tirelires.Controllers
{
    public class ProduitController : Controller
    {
        IRepository<Produit> rep = new EFRepositoryDerivative<Produit>();
        IRepository<Avi> repAvis = new EFRepository<Avi>();
        // GET: Produit
        public ActionResult Index()
        {
            IEnumerable<Produit> produits = rep.Lister();
            return View(produits);
        }

        // GET: Produit/Details/5
        public ActionResult Details(int id)
        {
            Produit p = rep.Trouver(id);
            PeuplerFournisseursViewData();
            return View(p);
        }

        // GET: Produit/Create
        public ActionResult Create()
        {
            PeuplerFournisseursViewData();
            return View();
        }
        private void PeuplerFournisseursViewData()
        {
            ViewData["IdFournisseur"] = new SelectList((new EFRepository<Fournisseur>()).Lister()
                , "Id", "Nom"
                );
        }
        // POST: Produit/Create
        [HttpPost,AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Produit p, HttpPostedFileBase fichier)
        {
            try
            {
                // TODO: Add insert logic here
                if (fichier != null && fichier.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(fichier.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Photos"), _FileName);
                    fichier.SaveAs(_path);
                    p.URLImage = "~/Photos/" + fichier.FileName;
                    rep.Ajouter(p);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                PeuplerFournisseursViewData();
                return View();
            }
        }

        // GET: Produit/Edit/5
        public ActionResult Edit(int id)
        {
            Produit p = rep.Trouver(id);
            PeuplerFournisseursViewData();
            return View(p);
        }

        // POST: Produit/Edit/5
        [HttpPost]
        public ActionResult Edit(Produit p, HttpPostedFileBase fichier)
        {
             
            try
            {
                
                // TODO: Add update logic here
                if (fichier != null && fichier.ContentLength>0)
                {
                    string _FileName = Path.GetFileName(fichier.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Photos"), _FileName);
                    fichier.SaveAs(_path);
                    p.URLImage = "~/Photos/"+fichier.FileName;
                    rep.Modifier(p);
                }
                else
                {
                    ViewBag.message = "Please Select Image";
                }
                
                return RedirectToAction("Index");
            }
            catch
            {
                PeuplerFournisseursViewData();
                return View();
            }
        }

        // GET: Produit/Delete/5
        public ActionResult Delete(int id)
        {
            Produit p = rep.Trouver(id);
            PeuplerFournisseursViewData();
            return View(p);
        }

        // POST: Produit/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // TODO: Add delete logic here
                rep.Supprimer(id);
                return RedirectToAction("Index");
            }
            catch
            {
                PeuplerFournisseursViewData();
                return View();
            }
        }
    }
}

Tirelires/Views/Produit/Create.cshtml
@model Tirelires.Produit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Produit", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "myForm", @role = "form" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdFournisseur, "IdFournisseur", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFournisseur", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdFournisseur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActived, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsActived, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poids, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poids, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poids, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URLImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URLImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URLImage, "", new { @class = "text-danger" })
                <input style="padding:15px" type="file" name="fichier" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hauteur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hauteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hauteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Largeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Largeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Largeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longueur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longueur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longueur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Couleur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Couleur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Couleur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tirelires/Views/Produit/Delete.cshtml
@model Tirelires.Produit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fournisseur.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fournisseur.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActived)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poids)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poids)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URLImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URLImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hauteur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hauteur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Largeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Largeur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longueur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longueur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Couleur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Couleur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tirelires/Views/Produit/Details.cshtml
@model Tirelires.Produit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Produit</h4>
    <hr />
    <div class="dl-horizontal">



        @*@Html.DisplayFor(model => model.URLImage)*@
        <img src="@Url.Content(Model.URLImage)" alt="image non trouvée" />
        <p class="float-right">
            @Html.ActionLink("Ajouter au Panier", "AjouterAuPanier", "Panier", new { id = Model.Id }, null)
        </p>
        <h6>
            @Html.DisplayFor(model => model.Nom)
        </h6>

        <p class="text-muted">
            de  @Html.DisplayFor(model => model.Fournisseur.Nom)

        </p>
        <p>

            @Html.DisplayFor(model => model.Description)
        </p>


        <p>
            @Html.DisplayNameFor(model => model.Prix) :
            <span class="font-weight-bold">
                @Html.DisplayFor(model => model.Prix)€
            </span>
        </p>



    <p>
        @Html.DisplayNameFor(model => model.UnitsInStock) : @Html.DisplayFor(model => model.UnitsInStock)
    </p>



    <p>
        @Html.DisplayNameFor(model => model.Poids)
        :
        @Html.DisplayFor(model => model.Poids)

    <p>
        @Html.DisplayNameFor(model => model.Hauteur)

        :

        @Html.DisplayFor(model => model.Hauteur)

    </p>
    <p>
        @Html.DisplayNameFor(model => model.Largeur)

        :
        @Html.DisplayFor(model => model.Largeur)

    </p>

    <p>
        @Html.DisplayNameFor(model => model.Longueur)
        :
        @Html.DisplayFor(model => model.Longueur)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Capacite)
        :
        @Html.DisplayFor(model => model.Capacite)
    </p>

    <p>
        @Html.DisplayNameFor(model => model.Couleur)
        :
        @Html.DisplayFor(model => model.Couleur)
    </p>




    </div>
    
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

Tirelires/Views/Produit/Edit.cshtml
@model Tirelires.Produit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Produit", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "myForm", @role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdFournisseur, "IdFournisseur", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFournisseur", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdFournisseur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActived)
                    @Html.ValidationMessageFor(model => model.IsActived, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poids, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poids, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poids, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URLImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URLImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URLImage, "", new { @class = "text-danger" })
                <input style="padding:15px" type="file" name="fichier" accept="image/x-png,image/gif,image/jpeg"/>
            </div>
            
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hauteur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hauteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hauteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Largeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Largeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Largeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longueur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longueur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longueur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Couleur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Couleur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Couleur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tirelires/Views/Produit/Index.cshtml
@model IEnumerable<Tirelires.Produit>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fournisseur.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActived)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Poids)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URLImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hauteur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Largeur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longueur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capacite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Couleur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fournisseur.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActived)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prix)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitsInStock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Poids)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.URLImage)*@
            <img src="@Url.Content(item.URLImage)" alt="image non trouvée" height="200"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hauteur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Largeur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longueur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capacite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Couleur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>

            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>